# Generated by Django 3.1.6 on 2021-03-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210304_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=43, verbose_name='Nome')),
                ('email', models.EmailField(max_length=43, verbose_name='E-mail')),
            ],
        ),
    ]
